services:
  qa-stand-login:
    build: .
    container_name: qa-stand-login
    restart: always
    env_file:
      - path: .env
        required: false
    ports:
      - "5000:80"
    volumes:
      - ~/.aws/:/root/.aws:ro
